#theme: jekyll-theme-minimal
logo: files/img/vicad_logo3.png
title: "Blog"
description: 'Russia, Moscow <br> Telegram: @the_vicad <br> Ex. Citibank, Curr. Sberbank'
footer: "&copy; 2024 Viktor Ponomarev"
homepage_label: "Homepage"
